### PR TITLE
Support Laravel 8

### PR DESCRIPTION
**Pull request by georgeboot**

### CODE REVIEW

**Comment by dwightwatson** [comment]
Thanks for this. I might merge this for now so it can be used from `dev-master`, but won't tag anything until Laravel 8 is officially tagged and we can test against it.

**Comment by tabuna** [comment]
Hey. I just wanted to remind you that the release of version 8 has already taken place.

**Comment by dwightwatson** [comment]
Thanks, sorting this out now.

**Comment by dwightwatson** [comment]
Just tagged `6.0.0`.

**Pull request merged**
