### PR TITLE
Fallback Class Functionality

### PR DESCRIPTION
**Pull request by Daikazu**
Added the ability to return a fallback css class if active is false. This comes in handy for utility CSS frameworks like Tailwind CSS.

### CODE REVIEW

**Comment by dwightwatson** [comment]
Hey, thanks for this. Do you think this needs to be added to the function signature, or is it something you could get away with using the ternary shorthand for? 

`active('home', 'active') ?: 'not-active'`

**Comment by Daikazu** [comment]
🤦‍♂️Having the additional argument as the return string seems more intuitive to me as you find this kind of stuff all over Laravel like in `config('MY_CONFIG_VAR', 'DEFAULT_VAR')` or `$request->input('foo', 'bar')`. But the ternary shorthand, which for some reason I never think of, would work just the same.

**Comment by dwightwatson** [comment]
Cool, not a huge change so I'll roll with it. Not sure what's up with the tests but I might just bump this bad boy to PHP 7+ and then it won't be an issue.

**Comment by Daikazu** [comment]
I was having trouble getting the test build running else I would of added the the test for that addition.

**Comment by dwightwatson** [comment]
Looks like the last commit was over a year ago so I think it's just aged poorly. 

I can't work out for the life of me how to re-merge master into this PR so I'll just merge and then sort it out - will tag a new major release shortly. Thanks again!

**Pull request merged**
