### PR TITLE
Added support laravel 7.0

### PR DESCRIPTION
**Pull request by tabuna**
Hey. The release of laravel 7.0 should take place on March 3rd, we can prepare it now. 
This does not require any code changes.

### CODE REVIEW

**Comment by dwightwatson** [comment]
Cool, thanks for this. Will rebuild, merge and tag on the 3rd.

Thanks for the PHP 7.4 PR too!

**Comment by timrspratt** [comment]
Can we get this tagged please 😊

**Comment by dwightwatson** [comment]
Thanks for your patience - Laravel 7.0 shipped during the middle of the night for me.

I've tagged `5.0.0`.

**Comment by andresayej** [comment]
@dwightwatson Thank you

**Pull request merged**
